// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: input_log.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace InputLogging {

  /// <summary>Holder for reflection information generated from input_log.proto</summary>
  public static partial class InputLogReflection {

    #region Descriptor
    /// <summary>File descriptor for input_log.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InputLogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9pbnB1dF9sb2cucHJvdG8SDElucHV0TG9nZ2luZyJrCgtMb2dNZXRhZGF0",
            "YRIyCipzeXN0ZW1fc3RvcHdhdGNoX3RpbWVzdGFtcF9hdF9raW5lY3Rfc3Rh",
            "cnQYASABKBISKAogZmlyc3Rfa2luZWN0X2RldmljZV90aW1lc3RhbXBfdXMY",
            "AiABKBIiwAEKFktleWJvYXJkRXZlbnREYXRhUHJvdG8SHwoXcmF3X3N0b3B3",
            "YXRjaF90aW1lc3RhbXAYASABKAQSGAoQdmlydHVhbF9rZXlfY29kZRgCIAEo",
            "DRIXCg9tb2RpZmllcnNfZmxhZ3MYAyABKA0SEwoLaXNfa2V5X2Rvd24YBCAB",
            "KAgiPQoQTW9kaWZpZXJLZXlTdGF0ZRIICgROT05FEAASBwoDQUxUEAESCwoH",
            "Q09OVFJPTBACEgkKBVNISUZUEAQiwAIKE01vdXNlRXZlbnREYXRhUHJvdG8S",
            "HwoXcmF3X3N0b3B3YXRjaF90aW1lc3RhbXAYASABKAQSPQoGYnV0dG9uGAIg",
            "ASgOMi0uSW5wdXRMb2dnaW5nLk1vdXNlRXZlbnREYXRhUHJvdG8uTW91c2VC",
            "dXR0b24SCQoBeBgDIAEoBRIJCgF5GAQgASgFEhMKC3doZWVsX2RlbHRhGAUg",
            "ASgFEhYKDmlzX2J1dHRvbl9kb3duGAYgASgIEhcKD2lzX21vdXNlX21vdmlu",
            "ZxgHIAEoCBIXCg9pc193aGVlbF9tb3ZpbmcYCCABKAgiVAoLTW91c2VCdXR0",
            "b24SCAoETk9ORRAAEggKBExFRlQQARIJCgVSSUdIVBACEgoKBk1JRERMRRAD",
            "EgwKCFhCVVRUT04xEAQSDAoIWEJVVFRPTjIQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::InputLogging.LogMetadata), global::InputLogging.LogMetadata.Parser, new[]{ "SystemStopwatchTimestampAtKinectStart", "FirstKinectDeviceTimestampUs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InputLogging.KeyboardEventDataProto), global::InputLogging.KeyboardEventDataProto.Parser, new[]{ "RawStopwatchTimestamp", "VirtualKeyCode", "ModifiersFlags", "IsKeyDown" }, null, new[]{ typeof(global::InputLogging.KeyboardEventDataProto.Types.ModifierKeyState) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InputLogging.MouseEventDataProto), global::InputLogging.MouseEventDataProto.Parser, new[]{ "RawStopwatchTimestamp", "Button", "X", "Y", "WheelDelta", "IsButtonDown", "IsMouseMoving", "IsWheelMoving" }, null, new[]{ typeof(global::InputLogging.MouseEventDataProto.Types.MouseButton) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LogMetadata : pb::IMessage<LogMetadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogMetadata> _parser = new pb::MessageParser<LogMetadata>(() => new LogMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InputLogging.InputLogReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogMetadata(LogMetadata other) : this() {
      systemStopwatchTimestampAtKinectStart_ = other.systemStopwatchTimestampAtKinectStart_;
      firstKinectDeviceTimestampUs_ = other.firstKinectDeviceTimestampUs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogMetadata Clone() {
      return new LogMetadata(this);
    }

    /// <summary>Field number for the "system_stopwatch_timestamp_at_kinect_start" field.</summary>
    public const int SystemStopwatchTimestampAtKinectStartFieldNumber = 1;
    private long systemStopwatchTimestampAtKinectStart_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SystemStopwatchTimestampAtKinectStart {
      get { return systemStopwatchTimestampAtKinectStart_; }
      set {
        systemStopwatchTimestampAtKinectStart_ = value;
      }
    }

    /// <summary>Field number for the "first_kinect_device_timestamp_us" field.</summary>
    public const int FirstKinectDeviceTimestampUsFieldNumber = 2;
    private long firstKinectDeviceTimestampUs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FirstKinectDeviceTimestampUs {
      get { return firstKinectDeviceTimestampUs_; }
      set {
        firstKinectDeviceTimestampUs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SystemStopwatchTimestampAtKinectStart != other.SystemStopwatchTimestampAtKinectStart) return false;
      if (FirstKinectDeviceTimestampUs != other.FirstKinectDeviceTimestampUs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SystemStopwatchTimestampAtKinectStart != 0L) hash ^= SystemStopwatchTimestampAtKinectStart.GetHashCode();
      if (FirstKinectDeviceTimestampUs != 0L) hash ^= FirstKinectDeviceTimestampUs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SystemStopwatchTimestampAtKinectStart != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(SystemStopwatchTimestampAtKinectStart);
      }
      if (FirstKinectDeviceTimestampUs != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(FirstKinectDeviceTimestampUs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SystemStopwatchTimestampAtKinectStart != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(SystemStopwatchTimestampAtKinectStart);
      }
      if (FirstKinectDeviceTimestampUs != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(FirstKinectDeviceTimestampUs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SystemStopwatchTimestampAtKinectStart != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(SystemStopwatchTimestampAtKinectStart);
      }
      if (FirstKinectDeviceTimestampUs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(FirstKinectDeviceTimestampUs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogMetadata other) {
      if (other == null) {
        return;
      }
      if (other.SystemStopwatchTimestampAtKinectStart != 0L) {
        SystemStopwatchTimestampAtKinectStart = other.SystemStopwatchTimestampAtKinectStart;
      }
      if (other.FirstKinectDeviceTimestampUs != 0L) {
        FirstKinectDeviceTimestampUs = other.FirstKinectDeviceTimestampUs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SystemStopwatchTimestampAtKinectStart = input.ReadSInt64();
            break;
          }
          case 16: {
            FirstKinectDeviceTimestampUs = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SystemStopwatchTimestampAtKinectStart = input.ReadSInt64();
            break;
          }
          case 16: {
            FirstKinectDeviceTimestampUs = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class KeyboardEventDataProto : pb::IMessage<KeyboardEventDataProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KeyboardEventDataProto> _parser = new pb::MessageParser<KeyboardEventDataProto>(() => new KeyboardEventDataProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KeyboardEventDataProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InputLogging.InputLogReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyboardEventDataProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyboardEventDataProto(KeyboardEventDataProto other) : this() {
      rawStopwatchTimestamp_ = other.rawStopwatchTimestamp_;
      virtualKeyCode_ = other.virtualKeyCode_;
      modifiersFlags_ = other.modifiersFlags_;
      isKeyDown_ = other.isKeyDown_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyboardEventDataProto Clone() {
      return new KeyboardEventDataProto(this);
    }

    /// <summary>Field number for the "raw_stopwatch_timestamp" field.</summary>
    public const int RawStopwatchTimestampFieldNumber = 1;
    private ulong rawStopwatchTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RawStopwatchTimestamp {
      get { return rawStopwatchTimestamp_; }
      set {
        rawStopwatchTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "virtual_key_code" field.</summary>
    public const int VirtualKeyCodeFieldNumber = 2;
    private uint virtualKeyCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint VirtualKeyCode {
      get { return virtualKeyCode_; }
      set {
        virtualKeyCode_ = value;
      }
    }

    /// <summary>Field number for the "modifiers_flags" field.</summary>
    public const int ModifiersFlagsFieldNumber = 3;
    private uint modifiersFlags_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ModifiersFlags {
      get { return modifiersFlags_; }
      set {
        modifiersFlags_ = value;
      }
    }

    /// <summary>Field number for the "is_key_down" field.</summary>
    public const int IsKeyDownFieldNumber = 4;
    private bool isKeyDown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsKeyDown {
      get { return isKeyDown_; }
      set {
        isKeyDown_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KeyboardEventDataProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KeyboardEventDataProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RawStopwatchTimestamp != other.RawStopwatchTimestamp) return false;
      if (VirtualKeyCode != other.VirtualKeyCode) return false;
      if (ModifiersFlags != other.ModifiersFlags) return false;
      if (IsKeyDown != other.IsKeyDown) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RawStopwatchTimestamp != 0UL) hash ^= RawStopwatchTimestamp.GetHashCode();
      if (VirtualKeyCode != 0) hash ^= VirtualKeyCode.GetHashCode();
      if (ModifiersFlags != 0) hash ^= ModifiersFlags.GetHashCode();
      if (IsKeyDown != false) hash ^= IsKeyDown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RawStopwatchTimestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(RawStopwatchTimestamp);
      }
      if (VirtualKeyCode != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(VirtualKeyCode);
      }
      if (ModifiersFlags != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ModifiersFlags);
      }
      if (IsKeyDown != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsKeyDown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RawStopwatchTimestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(RawStopwatchTimestamp);
      }
      if (VirtualKeyCode != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(VirtualKeyCode);
      }
      if (ModifiersFlags != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ModifiersFlags);
      }
      if (IsKeyDown != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsKeyDown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RawStopwatchTimestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RawStopwatchTimestamp);
      }
      if (VirtualKeyCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VirtualKeyCode);
      }
      if (ModifiersFlags != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ModifiersFlags);
      }
      if (IsKeyDown != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KeyboardEventDataProto other) {
      if (other == null) {
        return;
      }
      if (other.RawStopwatchTimestamp != 0UL) {
        RawStopwatchTimestamp = other.RawStopwatchTimestamp;
      }
      if (other.VirtualKeyCode != 0) {
        VirtualKeyCode = other.VirtualKeyCode;
      }
      if (other.ModifiersFlags != 0) {
        ModifiersFlags = other.ModifiersFlags;
      }
      if (other.IsKeyDown != false) {
        IsKeyDown = other.IsKeyDown;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RawStopwatchTimestamp = input.ReadUInt64();
            break;
          }
          case 16: {
            VirtualKeyCode = input.ReadUInt32();
            break;
          }
          case 24: {
            ModifiersFlags = input.ReadUInt32();
            break;
          }
          case 32: {
            IsKeyDown = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RawStopwatchTimestamp = input.ReadUInt64();
            break;
          }
          case 16: {
            VirtualKeyCode = input.ReadUInt32();
            break;
          }
          case 24: {
            ModifiersFlags = input.ReadUInt32();
            break;
          }
          case 32: {
            IsKeyDown = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the KeyboardEventDataProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ModifierKeyState {
        [pbr::OriginalName("NONE")] None = 0,
        [pbr::OriginalName("ALT")] Alt = 1,
        [pbr::OriginalName("CONTROL")] Control = 2,
        [pbr::OriginalName("SHIFT")] Shift = 4,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MouseEventDataProto : pb::IMessage<MouseEventDataProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MouseEventDataProto> _parser = new pb::MessageParser<MouseEventDataProto>(() => new MouseEventDataProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MouseEventDataProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InputLogging.InputLogReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseEventDataProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseEventDataProto(MouseEventDataProto other) : this() {
      rawStopwatchTimestamp_ = other.rawStopwatchTimestamp_;
      button_ = other.button_;
      x_ = other.x_;
      y_ = other.y_;
      wheelDelta_ = other.wheelDelta_;
      isButtonDown_ = other.isButtonDown_;
      isMouseMoving_ = other.isMouseMoving_;
      isWheelMoving_ = other.isWheelMoving_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseEventDataProto Clone() {
      return new MouseEventDataProto(this);
    }

    /// <summary>Field number for the "raw_stopwatch_timestamp" field.</summary>
    public const int RawStopwatchTimestampFieldNumber = 1;
    private ulong rawStopwatchTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RawStopwatchTimestamp {
      get { return rawStopwatchTimestamp_; }
      set {
        rawStopwatchTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "button" field.</summary>
    public const int ButtonFieldNumber = 2;
    private global::InputLogging.MouseEventDataProto.Types.MouseButton button_ = global::InputLogging.MouseEventDataProto.Types.MouseButton.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::InputLogging.MouseEventDataProto.Types.MouseButton Button {
      get { return button_; }
      set {
        button_ = value;
      }
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 3;
    private int x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 4;
    private int y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "wheel_delta" field.</summary>
    public const int WheelDeltaFieldNumber = 5;
    private int wheelDelta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WheelDelta {
      get { return wheelDelta_; }
      set {
        wheelDelta_ = value;
      }
    }

    /// <summary>Field number for the "is_button_down" field.</summary>
    public const int IsButtonDownFieldNumber = 6;
    private bool isButtonDown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsButtonDown {
      get { return isButtonDown_; }
      set {
        isButtonDown_ = value;
      }
    }

    /// <summary>Field number for the "is_mouse_moving" field.</summary>
    public const int IsMouseMovingFieldNumber = 7;
    private bool isMouseMoving_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsMouseMoving {
      get { return isMouseMoving_; }
      set {
        isMouseMoving_ = value;
      }
    }

    /// <summary>Field number for the "is_wheel_moving" field.</summary>
    public const int IsWheelMovingFieldNumber = 8;
    private bool isWheelMoving_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsWheelMoving {
      get { return isWheelMoving_; }
      set {
        isWheelMoving_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MouseEventDataProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MouseEventDataProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RawStopwatchTimestamp != other.RawStopwatchTimestamp) return false;
      if (Button != other.Button) return false;
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      if (WheelDelta != other.WheelDelta) return false;
      if (IsButtonDown != other.IsButtonDown) return false;
      if (IsMouseMoving != other.IsMouseMoving) return false;
      if (IsWheelMoving != other.IsWheelMoving) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RawStopwatchTimestamp != 0UL) hash ^= RawStopwatchTimestamp.GetHashCode();
      if (Button != global::InputLogging.MouseEventDataProto.Types.MouseButton.None) hash ^= Button.GetHashCode();
      if (X != 0) hash ^= X.GetHashCode();
      if (Y != 0) hash ^= Y.GetHashCode();
      if (WheelDelta != 0) hash ^= WheelDelta.GetHashCode();
      if (IsButtonDown != false) hash ^= IsButtonDown.GetHashCode();
      if (IsMouseMoving != false) hash ^= IsMouseMoving.GetHashCode();
      if (IsWheelMoving != false) hash ^= IsWheelMoving.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RawStopwatchTimestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(RawStopwatchTimestamp);
      }
      if (Button != global::InputLogging.MouseEventDataProto.Types.MouseButton.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Button);
      }
      if (X != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Y);
      }
      if (WheelDelta != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(WheelDelta);
      }
      if (IsButtonDown != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsButtonDown);
      }
      if (IsMouseMoving != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsMouseMoving);
      }
      if (IsWheelMoving != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsWheelMoving);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RawStopwatchTimestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(RawStopwatchTimestamp);
      }
      if (Button != global::InputLogging.MouseEventDataProto.Types.MouseButton.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Button);
      }
      if (X != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Y);
      }
      if (WheelDelta != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(WheelDelta);
      }
      if (IsButtonDown != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsButtonDown);
      }
      if (IsMouseMoving != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsMouseMoving);
      }
      if (IsWheelMoving != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsWheelMoving);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RawStopwatchTimestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RawStopwatchTimestamp);
      }
      if (Button != global::InputLogging.MouseEventDataProto.Types.MouseButton.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Button);
      }
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
      }
      if (WheelDelta != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WheelDelta);
      }
      if (IsButtonDown != false) {
        size += 1 + 1;
      }
      if (IsMouseMoving != false) {
        size += 1 + 1;
      }
      if (IsWheelMoving != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MouseEventDataProto other) {
      if (other == null) {
        return;
      }
      if (other.RawStopwatchTimestamp != 0UL) {
        RawStopwatchTimestamp = other.RawStopwatchTimestamp;
      }
      if (other.Button != global::InputLogging.MouseEventDataProto.Types.MouseButton.None) {
        Button = other.Button;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Y != 0) {
        Y = other.Y;
      }
      if (other.WheelDelta != 0) {
        WheelDelta = other.WheelDelta;
      }
      if (other.IsButtonDown != false) {
        IsButtonDown = other.IsButtonDown;
      }
      if (other.IsMouseMoving != false) {
        IsMouseMoving = other.IsMouseMoving;
      }
      if (other.IsWheelMoving != false) {
        IsWheelMoving = other.IsWheelMoving;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RawStopwatchTimestamp = input.ReadUInt64();
            break;
          }
          case 16: {
            Button = (global::InputLogging.MouseEventDataProto.Types.MouseButton) input.ReadEnum();
            break;
          }
          case 24: {
            X = input.ReadInt32();
            break;
          }
          case 32: {
            Y = input.ReadInt32();
            break;
          }
          case 40: {
            WheelDelta = input.ReadInt32();
            break;
          }
          case 48: {
            IsButtonDown = input.ReadBool();
            break;
          }
          case 56: {
            IsMouseMoving = input.ReadBool();
            break;
          }
          case 64: {
            IsWheelMoving = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RawStopwatchTimestamp = input.ReadUInt64();
            break;
          }
          case 16: {
            Button = (global::InputLogging.MouseEventDataProto.Types.MouseButton) input.ReadEnum();
            break;
          }
          case 24: {
            X = input.ReadInt32();
            break;
          }
          case 32: {
            Y = input.ReadInt32();
            break;
          }
          case 40: {
            WheelDelta = input.ReadInt32();
            break;
          }
          case 48: {
            IsButtonDown = input.ReadBool();
            break;
          }
          case 56: {
            IsMouseMoving = input.ReadBool();
            break;
          }
          case 64: {
            IsWheelMoving = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MouseEventDataProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum MouseButton {
        [pbr::OriginalName("NONE")] None = 0,
        [pbr::OriginalName("LEFT")] Left = 1,
        [pbr::OriginalName("RIGHT")] Right = 2,
        [pbr::OriginalName("MIDDLE")] Middle = 3,
        [pbr::OriginalName("XBUTTON1")] Xbutton1 = 4,
        [pbr::OriginalName("XBUTTON2")] Xbutton2 = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
