// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: holistic_landmarks.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HumanLandmarks {

  /// <summary>Holder for reflection information generated from holistic_landmarks.proto</summary>
  public static partial class HolisticLandmarksReflection {

    #region Descriptor
    /// <summary>File descriptor for holistic_landmarks.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HolisticLandmarksReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhob2xpc3RpY19sYW5kbWFya3MucHJvdG8SDmh1bWFuTGFuZG1hcmtzGhtr",
            "aW5lY3RfcG9zZV9sYW5kbWFya3MucHJvdG8aHm1lZGlhcGlwZV9wb3NlX2xh",
            "bmRtYXJrcy5wcm90bxoUaGFuZF9sYW5kbWFya3MucHJvdG8aEmZhY2VfcmVz",
            "dWx0cy5wcm90byLZAgoRSG9saXN0aWNMYW5kbWFya3MSQgoTa2luZWN0UG9z",
            "ZUxhbmRtYXJrcxgBIAEoCzIjLmh1bWFuTGFuZG1hcmtzLktpbmVjdFBvc2VM",
            "YW5kbWFya3NIABJIChZtZWRpYVBpcGVQb3NlTGFuZG1hcmtzGAUgASgLMiYu",
            "aHVtYW5MYW5kbWFya3MuTWVkaWFQaXBlUG9zZUxhbmRtYXJrc0gAEjgKEWxl",
            "ZnRIYW5kTGFuZG1hcmtzGAIgASgLMh0uaHVtYW5MYW5kbWFya3MuSGFuZExh",
            "bmRtYXJrcxI5ChJyaWdodEhhbmRMYW5kbWFya3MYAyABKAsyHS5odW1hbkxh",
            "bmRtYXJrcy5IYW5kTGFuZG1hcmtzEjAKC2ZhY2VSZXN1bHRzGAQgASgLMhsu",
            "aHVtYW5MYW5kbWFya3MuRmFjZVJlc3VsdHNCDwoNcG9zZUxhbmRtYXJrc2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HumanLandmarks.KinectPoseLandmarksReflection.Descriptor, global::HumanLandmarks.MediapipePoseLandmarksReflection.Descriptor, global::HumanLandmarks.HandLandmarksReflection.Descriptor, global::HumanLandmarks.FaceResultsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HumanLandmarks.HolisticLandmarks), global::HumanLandmarks.HolisticLandmarks.Parser, new[]{ "KinectPoseLandmarks", "MediaPipePoseLandmarks", "LeftHandLandmarks", "RightHandLandmarks", "FaceResults" }, new[]{ "PoseLandmarks" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HolisticLandmarks : pb::IMessage<HolisticLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HolisticLandmarks> _parser = new pb::MessageParser<HolisticLandmarks>(() => new HolisticLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HolisticLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HumanLandmarks.HolisticLandmarksReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks(HolisticLandmarks other) : this() {
      leftHandLandmarks_ = other.leftHandLandmarks_ != null ? other.leftHandLandmarks_.Clone() : null;
      rightHandLandmarks_ = other.rightHandLandmarks_ != null ? other.rightHandLandmarks_.Clone() : null;
      faceResults_ = other.faceResults_ != null ? other.faceResults_.Clone() : null;
      switch (other.PoseLandmarksCase) {
        case PoseLandmarksOneofCase.KinectPoseLandmarks:
          KinectPoseLandmarks = other.KinectPoseLandmarks.Clone();
          break;
        case PoseLandmarksOneofCase.MediaPipePoseLandmarks:
          MediaPipePoseLandmarks = other.MediaPipePoseLandmarks.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks Clone() {
      return new HolisticLandmarks(this);
    }

    /// <summary>Field number for the "kinectPoseLandmarks" field.</summary>
    public const int KinectPoseLandmarksFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.KinectPoseLandmarks KinectPoseLandmarks {
      get { return poseLandmarksCase_ == PoseLandmarksOneofCase.KinectPoseLandmarks ? (global::HumanLandmarks.KinectPoseLandmarks) poseLandmarks_ : null; }
      set {
        poseLandmarks_ = value;
        poseLandmarksCase_ = value == null ? PoseLandmarksOneofCase.None : PoseLandmarksOneofCase.KinectPoseLandmarks;
      }
    }

    /// <summary>Field number for the "mediaPipePoseLandmarks" field.</summary>
    public const int MediaPipePoseLandmarksFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.MediaPipePoseLandmarks MediaPipePoseLandmarks {
      get { return poseLandmarksCase_ == PoseLandmarksOneofCase.MediaPipePoseLandmarks ? (global::HumanLandmarks.MediaPipePoseLandmarks) poseLandmarks_ : null; }
      set {
        poseLandmarks_ = value;
        poseLandmarksCase_ = value == null ? PoseLandmarksOneofCase.None : PoseLandmarksOneofCase.MediaPipePoseLandmarks;
      }
    }

    /// <summary>Field number for the "leftHandLandmarks" field.</summary>
    public const int LeftHandLandmarksFieldNumber = 2;
    private global::HumanLandmarks.HandLandmarks leftHandLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.HandLandmarks LeftHandLandmarks {
      get { return leftHandLandmarks_; }
      set {
        leftHandLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "rightHandLandmarks" field.</summary>
    public const int RightHandLandmarksFieldNumber = 3;
    private global::HumanLandmarks.HandLandmarks rightHandLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.HandLandmarks RightHandLandmarks {
      get { return rightHandLandmarks_; }
      set {
        rightHandLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "faceResults" field.</summary>
    public const int FaceResultsFieldNumber = 4;
    private global::HumanLandmarks.FaceResults faceResults_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.FaceResults FaceResults {
      get { return faceResults_; }
      set {
        faceResults_ = value;
      }
    }

    private object poseLandmarks_;
    /// <summary>Enum of possible cases for the "poseLandmarks" oneof.</summary>
    public enum PoseLandmarksOneofCase {
      None = 0,
      KinectPoseLandmarks = 1,
      MediaPipePoseLandmarks = 5,
    }
    private PoseLandmarksOneofCase poseLandmarksCase_ = PoseLandmarksOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoseLandmarksOneofCase PoseLandmarksCase {
      get { return poseLandmarksCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPoseLandmarks() {
      poseLandmarksCase_ = PoseLandmarksOneofCase.None;
      poseLandmarks_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HolisticLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HolisticLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(KinectPoseLandmarks, other.KinectPoseLandmarks)) return false;
      if (!object.Equals(MediaPipePoseLandmarks, other.MediaPipePoseLandmarks)) return false;
      if (!object.Equals(LeftHandLandmarks, other.LeftHandLandmarks)) return false;
      if (!object.Equals(RightHandLandmarks, other.RightHandLandmarks)) return false;
      if (!object.Equals(FaceResults, other.FaceResults)) return false;
      if (PoseLandmarksCase != other.PoseLandmarksCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (poseLandmarksCase_ == PoseLandmarksOneofCase.KinectPoseLandmarks) hash ^= KinectPoseLandmarks.GetHashCode();
      if (poseLandmarksCase_ == PoseLandmarksOneofCase.MediaPipePoseLandmarks) hash ^= MediaPipePoseLandmarks.GetHashCode();
      if (leftHandLandmarks_ != null) hash ^= LeftHandLandmarks.GetHashCode();
      if (rightHandLandmarks_ != null) hash ^= RightHandLandmarks.GetHashCode();
      if (faceResults_ != null) hash ^= FaceResults.GetHashCode();
      hash ^= (int) poseLandmarksCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (poseLandmarksCase_ == PoseLandmarksOneofCase.KinectPoseLandmarks) {
        output.WriteRawTag(10);
        output.WriteMessage(KinectPoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceResults);
      }
      if (poseLandmarksCase_ == PoseLandmarksOneofCase.MediaPipePoseLandmarks) {
        output.WriteRawTag(42);
        output.WriteMessage(MediaPipePoseLandmarks);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (poseLandmarksCase_ == PoseLandmarksOneofCase.KinectPoseLandmarks) {
        output.WriteRawTag(10);
        output.WriteMessage(KinectPoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceResults);
      }
      if (poseLandmarksCase_ == PoseLandmarksOneofCase.MediaPipePoseLandmarks) {
        output.WriteRawTag(42);
        output.WriteMessage(MediaPipePoseLandmarks);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (poseLandmarksCase_ == PoseLandmarksOneofCase.KinectPoseLandmarks) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(KinectPoseLandmarks);
      }
      if (poseLandmarksCase_ == PoseLandmarksOneofCase.MediaPipePoseLandmarks) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MediaPipePoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceResults);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HolisticLandmarks other) {
      if (other == null) {
        return;
      }
      if (other.leftHandLandmarks_ != null) {
        if (leftHandLandmarks_ == null) {
          LeftHandLandmarks = new global::HumanLandmarks.HandLandmarks();
        }
        LeftHandLandmarks.MergeFrom(other.LeftHandLandmarks);
      }
      if (other.rightHandLandmarks_ != null) {
        if (rightHandLandmarks_ == null) {
          RightHandLandmarks = new global::HumanLandmarks.HandLandmarks();
        }
        RightHandLandmarks.MergeFrom(other.RightHandLandmarks);
      }
      if (other.faceResults_ != null) {
        if (faceResults_ == null) {
          FaceResults = new global::HumanLandmarks.FaceResults();
        }
        FaceResults.MergeFrom(other.FaceResults);
      }
      switch (other.PoseLandmarksCase) {
        case PoseLandmarksOneofCase.KinectPoseLandmarks:
          if (KinectPoseLandmarks == null) {
            KinectPoseLandmarks = new global::HumanLandmarks.KinectPoseLandmarks();
          }
          KinectPoseLandmarks.MergeFrom(other.KinectPoseLandmarks);
          break;
        case PoseLandmarksOneofCase.MediaPipePoseLandmarks:
          if (MediaPipePoseLandmarks == null) {
            MediaPipePoseLandmarks = new global::HumanLandmarks.MediaPipePoseLandmarks();
          }
          MediaPipePoseLandmarks.MergeFrom(other.MediaPipePoseLandmarks);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::HumanLandmarks.KinectPoseLandmarks subBuilder = new global::HumanLandmarks.KinectPoseLandmarks();
            if (poseLandmarksCase_ == PoseLandmarksOneofCase.KinectPoseLandmarks) {
              subBuilder.MergeFrom(KinectPoseLandmarks);
            }
            input.ReadMessage(subBuilder);
            KinectPoseLandmarks = subBuilder;
            break;
          }
          case 18: {
            if (leftHandLandmarks_ == null) {
              LeftHandLandmarks = new global::HumanLandmarks.HandLandmarks();
            }
            input.ReadMessage(LeftHandLandmarks);
            break;
          }
          case 26: {
            if (rightHandLandmarks_ == null) {
              RightHandLandmarks = new global::HumanLandmarks.HandLandmarks();
            }
            input.ReadMessage(RightHandLandmarks);
            break;
          }
          case 34: {
            if (faceResults_ == null) {
              FaceResults = new global::HumanLandmarks.FaceResults();
            }
            input.ReadMessage(FaceResults);
            break;
          }
          case 42: {
            global::HumanLandmarks.MediaPipePoseLandmarks subBuilder = new global::HumanLandmarks.MediaPipePoseLandmarks();
            if (poseLandmarksCase_ == PoseLandmarksOneofCase.MediaPipePoseLandmarks) {
              subBuilder.MergeFrom(MediaPipePoseLandmarks);
            }
            input.ReadMessage(subBuilder);
            MediaPipePoseLandmarks = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::HumanLandmarks.KinectPoseLandmarks subBuilder = new global::HumanLandmarks.KinectPoseLandmarks();
            if (poseLandmarksCase_ == PoseLandmarksOneofCase.KinectPoseLandmarks) {
              subBuilder.MergeFrom(KinectPoseLandmarks);
            }
            input.ReadMessage(subBuilder);
            KinectPoseLandmarks = subBuilder;
            break;
          }
          case 18: {
            if (leftHandLandmarks_ == null) {
              LeftHandLandmarks = new global::HumanLandmarks.HandLandmarks();
            }
            input.ReadMessage(LeftHandLandmarks);
            break;
          }
          case 26: {
            if (rightHandLandmarks_ == null) {
              RightHandLandmarks = new global::HumanLandmarks.HandLandmarks();
            }
            input.ReadMessage(RightHandLandmarks);
            break;
          }
          case 34: {
            if (faceResults_ == null) {
              FaceResults = new global::HumanLandmarks.FaceResults();
            }
            input.ReadMessage(FaceResults);
            break;
          }
          case 42: {
            global::HumanLandmarks.MediaPipePoseLandmarks subBuilder = new global::HumanLandmarks.MediaPipePoseLandmarks();
            if (poseLandmarksCase_ == PoseLandmarksOneofCase.MediaPipePoseLandmarks) {
              subBuilder.MergeFrom(MediaPipePoseLandmarks);
            }
            input.ReadMessage(subBuilder);
            MediaPipePoseLandmarks = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
