// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: landmark_log.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HumanLandmarks.Log {

  /// <summary>Holder for reflection information generated from landmark_log.proto</summary>
  public static partial class LandmarkLogReflection {

    #region Descriptor
    /// <summary>File descriptor for landmark_log.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LandmarkLogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJsYW5kbWFya19sb2cucHJvdG8SEmh1bWFuTGFuZG1hcmtzLmxvZxoYaG9s",
            "aXN0aWNfbGFuZG1hcmtzLnByb3RvIvMCChBDb29yZGluYXRlU3lzdGVtEgwK",
            "BHVuaXQYASABKAkSPwoHdXBfYXhpcxgCIAEoDjIuLmh1bWFuTGFuZG1hcmtz",
            "LmxvZy5Db29yZGluYXRlU3lzdGVtLkRpcmVjdGlvbhJCCgpyaWdodF9heGlz",
            "GAMgASgOMi4uaHVtYW5MYW5kbWFya3MubG9nLkNvb3JkaW5hdGVTeXN0ZW0u",
            "RGlyZWN0aW9uEkMKCmhhbmRlZG5lc3MYBCABKA4yLy5odW1hbkxhbmRtYXJr",
            "cy5sb2cuQ29vcmRpbmF0ZVN5c3RlbS5IYW5kZWRuZXNzIlYKCURpcmVjdGlv",
            "bhIKCgZYX1BMVVMQABILCgdYX01JTlVTEAESCgoGWV9QTFVTEAISCwoHWV9N",
            "SU5VUxADEgoKBlpfUExVUxAEEgsKB1pfTUlOVVMQBSIvCgpIYW5kZWRuZXNz",
            "EhAKDFJJR0hUX0hBTkRFRBAAEg8KC0xFRlRfSEFOREVEEAEihwEKCUxvZ0hl",
            "YWRlchIaChJsb2dfc2NoZW1hX3ZlcnNpb24YASABKAkSHQoVY2FwdHVyZV9m",
            "cmFtZXJhdGVfZnBzGAIgASgFEj8KEWNvb3JkaW5hdGVfc3lzdGVtGAMgASgL",
            "MiQuaHVtYW5MYW5kbWFya3MubG9nLkNvb3JkaW5hdGVTeXN0ZW0ieQoMTG9n",
            "RnJhbWVEYXRhEhQKDHRpbWVzdGFtcF9tcxgBIAEoARIUCgxmcmFtZV9udW1i",
            "ZXIYAiABKA0SPQoSaG9saXN0aWNfbGFuZG1hcmtzGAMgASgLMiEuaHVtYW5M",
            "YW5kbWFya3MuSG9saXN0aWNMYW5kbWFya3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HumanLandmarks.HolisticLandmarksReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HumanLandmarks.Log.CoordinateSystem), global::HumanLandmarks.Log.CoordinateSystem.Parser, new[]{ "Unit", "UpAxis", "RightAxis", "Handedness" }, null, new[]{ typeof(global::HumanLandmarks.Log.CoordinateSystem.Types.Direction), typeof(global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HumanLandmarks.Log.LogHeader), global::HumanLandmarks.Log.LogHeader.Parser, new[]{ "LogSchemaVersion", "CaptureFramerateFps", "CoordinateSystem" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HumanLandmarks.Log.LogFrameData), global::HumanLandmarks.Log.LogFrameData.Parser, new[]{ "TimestampMs", "FrameNumber", "HolisticLandmarks" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CoordinateSystem : pb::IMessage<CoordinateSystem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CoordinateSystem> _parser = new pb::MessageParser<CoordinateSystem>(() => new CoordinateSystem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CoordinateSystem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HumanLandmarks.Log.LandmarkLogReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CoordinateSystem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CoordinateSystem(CoordinateSystem other) : this() {
      unit_ = other.unit_;
      upAxis_ = other.upAxis_;
      rightAxis_ = other.rightAxis_;
      handedness_ = other.handedness_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CoordinateSystem Clone() {
      return new CoordinateSystem(this);
    }

    /// <summary>Field number for the "unit" field.</summary>
    public const int UnitFieldNumber = 1;
    private string unit_ = "";
    /// <summary>
    /// e.g. "meter", "milli meter"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Unit {
      get { return unit_; }
      set {
        unit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "up_axis" field.</summary>
    public const int UpAxisFieldNumber = 2;
    private global::HumanLandmarks.Log.CoordinateSystem.Types.Direction upAxis_ = global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.Log.CoordinateSystem.Types.Direction UpAxis {
      get { return upAxis_; }
      set {
        upAxis_ = value;
      }
    }

    /// <summary>Field number for the "right_axis" field.</summary>
    public const int RightAxisFieldNumber = 3;
    private global::HumanLandmarks.Log.CoordinateSystem.Types.Direction rightAxis_ = global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.Log.CoordinateSystem.Types.Direction RightAxis {
      get { return rightAxis_; }
      set {
        rightAxis_ = value;
      }
    }

    /// <summary>Field number for the "handedness" field.</summary>
    public const int HandednessFieldNumber = 4;
    private global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness handedness_ = global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness.RightHanded;
    /// <summary>
    /// For 2D estimations, this value should be disregarded.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness Handedness {
      get { return handedness_; }
      set {
        handedness_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CoordinateSystem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CoordinateSystem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unit != other.Unit) return false;
      if (UpAxis != other.UpAxis) return false;
      if (RightAxis != other.RightAxis) return false;
      if (Handedness != other.Handedness) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Unit.Length != 0) hash ^= Unit.GetHashCode();
      if (UpAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) hash ^= UpAxis.GetHashCode();
      if (RightAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) hash ^= RightAxis.GetHashCode();
      if (Handedness != global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness.RightHanded) hash ^= Handedness.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Unit.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Unit);
      }
      if (UpAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UpAxis);
      }
      if (RightAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) {
        output.WriteRawTag(24);
        output.WriteEnum((int) RightAxis);
      }
      if (Handedness != global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness.RightHanded) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Handedness);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Unit.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Unit);
      }
      if (UpAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UpAxis);
      }
      if (RightAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) {
        output.WriteRawTag(24);
        output.WriteEnum((int) RightAxis);
      }
      if (Handedness != global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness.RightHanded) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Handedness);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Unit.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Unit);
      }
      if (UpAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UpAxis);
      }
      if (RightAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RightAxis);
      }
      if (Handedness != global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness.RightHanded) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Handedness);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CoordinateSystem other) {
      if (other == null) {
        return;
      }
      if (other.Unit.Length != 0) {
        Unit = other.Unit;
      }
      if (other.UpAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) {
        UpAxis = other.UpAxis;
      }
      if (other.RightAxis != global::HumanLandmarks.Log.CoordinateSystem.Types.Direction.XPlus) {
        RightAxis = other.RightAxis;
      }
      if (other.Handedness != global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness.RightHanded) {
        Handedness = other.Handedness;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Unit = input.ReadString();
            break;
          }
          case 16: {
            UpAxis = (global::HumanLandmarks.Log.CoordinateSystem.Types.Direction) input.ReadEnum();
            break;
          }
          case 24: {
            RightAxis = (global::HumanLandmarks.Log.CoordinateSystem.Types.Direction) input.ReadEnum();
            break;
          }
          case 32: {
            Handedness = (global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Unit = input.ReadString();
            break;
          }
          case 16: {
            UpAxis = (global::HumanLandmarks.Log.CoordinateSystem.Types.Direction) input.ReadEnum();
            break;
          }
          case 24: {
            RightAxis = (global::HumanLandmarks.Log.CoordinateSystem.Types.Direction) input.ReadEnum();
            break;
          }
          case 32: {
            Handedness = (global::HumanLandmarks.Log.CoordinateSystem.Types.Handedness) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CoordinateSystem message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Direction {
        [pbr::OriginalName("X_PLUS")] XPlus = 0,
        [pbr::OriginalName("X_MINUS")] XMinus = 1,
        [pbr::OriginalName("Y_PLUS")] YPlus = 2,
        [pbr::OriginalName("Y_MINUS")] YMinus = 3,
        [pbr::OriginalName("Z_PLUS")] ZPlus = 4,
        [pbr::OriginalName("Z_MINUS")] ZMinus = 5,
      }

      public enum Handedness {
        [pbr::OriginalName("RIGHT_HANDED")] RightHanded = 0,
        [pbr::OriginalName("LEFT_HANDED")] LeftHanded = 1,
      }

    }
    #endregion

  }

  /// <summary>
  /// recorded once in head of the log file
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LogHeader : pb::IMessage<LogHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogHeader> _parser = new pb::MessageParser<LogHeader>(() => new LogHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HumanLandmarks.Log.LandmarkLogReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogHeader(LogHeader other) : this() {
      logSchemaVersion_ = other.logSchemaVersion_;
      captureFramerateFps_ = other.captureFramerateFps_;
      coordinateSystem_ = other.coordinateSystem_ != null ? other.coordinateSystem_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogHeader Clone() {
      return new LogHeader(this);
    }

    /// <summary>Field number for the "log_schema_version" field.</summary>
    public const int LogSchemaVersionFieldNumber = 1;
    private string logSchemaVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LogSchemaVersion {
      get { return logSchemaVersion_; }
      set {
        logSchemaVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "capture_framerate_fps" field.</summary>
    public const int CaptureFramerateFpsFieldNumber = 2;
    private int captureFramerateFps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CaptureFramerateFps {
      get { return captureFramerateFps_; }
      set {
        captureFramerateFps_ = value;
      }
    }

    /// <summary>Field number for the "coordinate_system" field.</summary>
    public const int CoordinateSystemFieldNumber = 3;
    private global::HumanLandmarks.Log.CoordinateSystem coordinateSystem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.Log.CoordinateSystem CoordinateSystem {
      get { return coordinateSystem_; }
      set {
        coordinateSystem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LogSchemaVersion != other.LogSchemaVersion) return false;
      if (CaptureFramerateFps != other.CaptureFramerateFps) return false;
      if (!object.Equals(CoordinateSystem, other.CoordinateSystem)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LogSchemaVersion.Length != 0) hash ^= LogSchemaVersion.GetHashCode();
      if (CaptureFramerateFps != 0) hash ^= CaptureFramerateFps.GetHashCode();
      if (coordinateSystem_ != null) hash ^= CoordinateSystem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LogSchemaVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LogSchemaVersion);
      }
      if (CaptureFramerateFps != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CaptureFramerateFps);
      }
      if (coordinateSystem_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CoordinateSystem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LogSchemaVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LogSchemaVersion);
      }
      if (CaptureFramerateFps != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CaptureFramerateFps);
      }
      if (coordinateSystem_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CoordinateSystem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LogSchemaVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LogSchemaVersion);
      }
      if (CaptureFramerateFps != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CaptureFramerateFps);
      }
      if (coordinateSystem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CoordinateSystem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogHeader other) {
      if (other == null) {
        return;
      }
      if (other.LogSchemaVersion.Length != 0) {
        LogSchemaVersion = other.LogSchemaVersion;
      }
      if (other.CaptureFramerateFps != 0) {
        CaptureFramerateFps = other.CaptureFramerateFps;
      }
      if (other.coordinateSystem_ != null) {
        if (coordinateSystem_ == null) {
          CoordinateSystem = new global::HumanLandmarks.Log.CoordinateSystem();
        }
        CoordinateSystem.MergeFrom(other.CoordinateSystem);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LogSchemaVersion = input.ReadString();
            break;
          }
          case 16: {
            CaptureFramerateFps = input.ReadInt32();
            break;
          }
          case 26: {
            if (coordinateSystem_ == null) {
              CoordinateSystem = new global::HumanLandmarks.Log.CoordinateSystem();
            }
            input.ReadMessage(CoordinateSystem);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            LogSchemaVersion = input.ReadString();
            break;
          }
          case 16: {
            CaptureFramerateFps = input.ReadInt32();
            break;
          }
          case 26: {
            if (coordinateSystem_ == null) {
              CoordinateSystem = new global::HumanLandmarks.Log.CoordinateSystem();
            }
            input.ReadMessage(CoordinateSystem);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// recorded in each of frame
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LogFrameData : pb::IMessage<LogFrameData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogFrameData> _parser = new pb::MessageParser<LogFrameData>(() => new LogFrameData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogFrameData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HumanLandmarks.Log.LandmarkLogReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFrameData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFrameData(LogFrameData other) : this() {
      timestampMs_ = other.timestampMs_;
      frameNumber_ = other.frameNumber_;
      holisticLandmarks_ = other.holisticLandmarks_ != null ? other.holisticLandmarks_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFrameData Clone() {
      return new LogFrameData(this);
    }

    /// <summary>Field number for the "timestamp_ms" field.</summary>
    public const int TimestampMsFieldNumber = 1;
    private double timestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TimestampMs {
      get { return timestampMs_; }
      set {
        timestampMs_ = value;
      }
    }

    /// <summary>Field number for the "frame_number" field.</summary>
    public const int FrameNumberFieldNumber = 2;
    private uint frameNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrameNumber {
      get { return frameNumber_; }
      set {
        frameNumber_ = value;
      }
    }

    /// <summary>Field number for the "holistic_landmarks" field.</summary>
    public const int HolisticLandmarksFieldNumber = 3;
    private global::HumanLandmarks.HolisticLandmarks holisticLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.HolisticLandmarks HolisticLandmarks {
      get { return holisticLandmarks_; }
      set {
        holisticLandmarks_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogFrameData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogFrameData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TimestampMs, other.TimestampMs)) return false;
      if (FrameNumber != other.FrameNumber) return false;
      if (!object.Equals(HolisticLandmarks, other.HolisticLandmarks)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TimestampMs != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TimestampMs);
      if (FrameNumber != 0) hash ^= FrameNumber.GetHashCode();
      if (holisticLandmarks_ != null) hash ^= HolisticLandmarks.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TimestampMs != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TimestampMs);
      }
      if (FrameNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(FrameNumber);
      }
      if (holisticLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(HolisticLandmarks);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TimestampMs != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TimestampMs);
      }
      if (FrameNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(FrameNumber);
      }
      if (holisticLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(HolisticLandmarks);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TimestampMs != 0D) {
        size += 1 + 8;
      }
      if (FrameNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FrameNumber);
      }
      if (holisticLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HolisticLandmarks);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogFrameData other) {
      if (other == null) {
        return;
      }
      if (other.TimestampMs != 0D) {
        TimestampMs = other.TimestampMs;
      }
      if (other.FrameNumber != 0) {
        FrameNumber = other.FrameNumber;
      }
      if (other.holisticLandmarks_ != null) {
        if (holisticLandmarks_ == null) {
          HolisticLandmarks = new global::HumanLandmarks.HolisticLandmarks();
        }
        HolisticLandmarks.MergeFrom(other.HolisticLandmarks);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            TimestampMs = input.ReadDouble();
            break;
          }
          case 16: {
            FrameNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            if (holisticLandmarks_ == null) {
              HolisticLandmarks = new global::HumanLandmarks.HolisticLandmarks();
            }
            input.ReadMessage(HolisticLandmarks);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            TimestampMs = input.ReadDouble();
            break;
          }
          case 16: {
            FrameNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            if (holisticLandmarks_ == null) {
              HolisticLandmarks = new global::HumanLandmarks.HolisticLandmarks();
            }
            input.ReadMessage(HolisticLandmarks);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
