// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe_pose_landmarks.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HumanLandmarks {

  /// <summary>Holder for reflection information generated from mediapipe_pose_landmarks.proto</summary>
  public static partial class MediapipePoseLandmarksReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe_pose_landmarks.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MediapipePoseLandmarksReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5tZWRpYXBpcGVfcG9zZV9sYW5kbWFya3MucHJvdG8SDmh1bWFuTGFuZG1h",
            "cmtzGg5sYW5kbWFyay5wcm90byLsBAoWTWVkaWFQaXBlUG9zZUxhbmRtYXJr",
            "cxIwCglsYW5kbWFya3MYASADKAsyHS5odW1hbkxhbmRtYXJrcy5MYW5kbWFy",
            "a1BvaW50Ip8ECg1MYW5kbWFya0luZGV4EggKBG5vc2UQABIQCgxsZWZ0RXll",
            "SW5uZXIQARILCgdsZWZ0RXllEAISEAoMbGVmdEV5ZU91dGVyEAMSEQoNcmln",
            "aHRFeWVJbm5lchAEEgwKCHJpZ2h0RXllEAUSEQoNcmlnaHRFeWVPdXRlchAG",
            "EgsKB2xlZnRFYXIQBxIMCghyaWdodEVhchAIEg0KCW1vdXRoTGVmdBAJEg4K",
            "Cm1vdXRoUmlnaHQQChIQCgxsZWZ0U2hvdWxkZXIQCxIRCg1yaWdodFNob3Vs",
            "ZGVyEAwSDQoJbGVmdEVsYm93EA0SDgoKcmlnaHRFbGJvdxAOEg0KCWxlZnRX",
            "cmlzdBAPEg4KCnJpZ2h0V3Jpc3QQEBINCglsZWZ0UGlua3kQERIOCgpyaWdo",
            "dFBpbmt5EBISDQoJbGVmdEluZGV4EBMSDgoKcmlnaHRJbmRleBAUEg0KCWxl",
            "ZnRUaHVtYhAVEg4KCnJpZ2h0VGh1bWIQFhILCgdsZWZ0SGlwEBcSDAoIcmln",
            "aHRIaXAQGBIMCghsZWZ0S25lZRAZEg0KCXJpZ2h0S25lZRAaEg0KCWxlZnRB",
            "bmtsZRAbEg4KCnJpZ2h0QW5rbGUQHBIMCghsZWZ0SGVlbBAdEg0KCXJpZ2h0",
            "SGVlbBAeEhEKDWxlZnRGb290SW5kZXgQHxISCg5yaWdodEZvb3RJbmRleBAg",
            "EgoKBmxlbmd0aBAhYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HumanLandmarks.LandmarkReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HumanLandmarks.MediaPipePoseLandmarks), global::HumanLandmarks.MediaPipePoseLandmarks.Parser, new[]{ "Landmarks" }, null, new[]{ typeof(global::HumanLandmarks.MediaPipePoseLandmarks.Types.LandmarkIndex) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MediaPipePoseLandmarks : pb::IMessage<MediaPipePoseLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MediaPipePoseLandmarks> _parser = new pb::MessageParser<MediaPipePoseLandmarks>(() => new MediaPipePoseLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MediaPipePoseLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HumanLandmarks.MediapipePoseLandmarksReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MediaPipePoseLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MediaPipePoseLandmarks(MediaPipePoseLandmarks other) : this() {
      landmarks_ = other.landmarks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MediaPipePoseLandmarks Clone() {
      return new MediaPipePoseLandmarks(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HumanLandmarks.LandmarkPoint> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HumanLandmarks.LandmarkPoint.Parser);
    private readonly pbc::RepeatedField<global::HumanLandmarks.LandmarkPoint> landmarks_ = new pbc::RepeatedField<global::HumanLandmarks.LandmarkPoint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HumanLandmarks.LandmarkPoint> Landmarks {
      get { return landmarks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MediaPipePoseLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MediaPipePoseLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MediaPipePoseLandmarks other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MediaPipePoseLandmarks message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum LandmarkIndex {
        [pbr::OriginalName("nose")] Nose = 0,
        [pbr::OriginalName("leftEyeInner")] LeftEyeInner = 1,
        [pbr::OriginalName("leftEye")] LeftEye = 2,
        [pbr::OriginalName("leftEyeOuter")] LeftEyeOuter = 3,
        [pbr::OriginalName("rightEyeInner")] RightEyeInner = 4,
        [pbr::OriginalName("rightEye")] RightEye = 5,
        [pbr::OriginalName("rightEyeOuter")] RightEyeOuter = 6,
        [pbr::OriginalName("leftEar")] LeftEar = 7,
        [pbr::OriginalName("rightEar")] RightEar = 8,
        [pbr::OriginalName("mouthLeft")] MouthLeft = 9,
        [pbr::OriginalName("mouthRight")] MouthRight = 10,
        [pbr::OriginalName("leftShoulder")] LeftShoulder = 11,
        [pbr::OriginalName("rightShoulder")] RightShoulder = 12,
        [pbr::OriginalName("leftElbow")] LeftElbow = 13,
        [pbr::OriginalName("rightElbow")] RightElbow = 14,
        [pbr::OriginalName("leftWrist")] LeftWrist = 15,
        [pbr::OriginalName("rightWrist")] RightWrist = 16,
        [pbr::OriginalName("leftPinky")] LeftPinky = 17,
        [pbr::OriginalName("rightPinky")] RightPinky = 18,
        [pbr::OriginalName("leftIndex")] LeftIndex = 19,
        [pbr::OriginalName("rightIndex")] RightIndex = 20,
        [pbr::OriginalName("leftThumb")] LeftThumb = 21,
        [pbr::OriginalName("rightThumb")] RightThumb = 22,
        [pbr::OriginalName("leftHip")] LeftHip = 23,
        [pbr::OriginalName("rightHip")] RightHip = 24,
        [pbr::OriginalName("leftKnee")] LeftKnee = 25,
        [pbr::OriginalName("rightKnee")] RightKnee = 26,
        [pbr::OriginalName("leftAnkle")] LeftAnkle = 27,
        [pbr::OriginalName("rightAnkle")] RightAnkle = 28,
        [pbr::OriginalName("leftHeel")] LeftHeel = 29,
        [pbr::OriginalName("rightHeel")] RightHeel = 30,
        [pbr::OriginalName("leftFootIndex")] LeftFootIndex = 31,
        [pbr::OriginalName("rightFootIndex")] RightFootIndex = 32,
        [pbr::OriginalName("length")] Length = 33,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
