// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: face_results.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HumanLandmarks {

  /// <summary>Holder for reflection information generated from face_results.proto</summary>
  public static partial class FaceResultsReflection {

    #region Descriptor
    /// <summary>File descriptor for face_results.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FaceResultsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJmYWNlX3Jlc3VsdHMucHJvdG8SDmh1bWFuTGFuZG1hcmtzGg5sYW5kbWFy",
            "ay5wcm90byJsCgtGYWNlUmVzdWx0cxIrCglsYW5kbWFya3MYASADKAsyGC5o",
            "dW1hbkxhbmRtYXJrcy5MYW5kbWFyaxIwCgtibGVuZHNoYXBlcxgCIAEoCzIb",
            "Lmh1bWFuTGFuZG1hcmtzLkJsZW5kc2hhcGVzIsQICgtCbGVuZHNoYXBlcxIO",
            "CgZzY29yZXMYASADKAIipAgKEEJsZW5kc2hhcGVzSW5kZXgSDAoIX25ldXRy",
            "YWwQABIQCgxicm93RG93bkxlZnQQARIRCg1icm93RG93blJpZ2h0EAISDwoL",
            "YnJvd0lubmVyVXAQAxITCg9icm93T3V0ZXJVcExlZnQQBBIUChBicm93T3V0",
            "ZXJVcFJpZ2h0EAUSDQoJY2hlZWtQdWZmEAYSEwoPY2hlZWtTcXVpbnRMZWZ0",
            "EAcSFAoQY2hlZWtTcXVpbnRSaWdodBAIEhAKDGV5ZUJsaW5rTGVmdBAJEhEK",
            "DWV5ZUJsaW5rUmlnaHQQChITCg9leWVMb29rRG93bkxlZnQQCxIUChBleWVM",
            "b29rRG93blJpZ2h0EAwSEQoNZXllTG9va0luTGVmdBANEhIKDmV5ZUxvb2tJ",
            "blJpZ2h0EA4SEgoOZXllTG9va091dExlZnQQDxITCg9leWVMb29rT3V0Umln",
            "aHQQEBIRCg1leWVMb29rVXBMZWZ0EBESEgoOZXllTG9va1VwUmlnaHQQEhIR",
            "Cg1leWVTcXVpbnRMZWZ0EBMSEgoOZXllU3F1aW50UmlnaHQQFBIPCgtleWVX",
            "aWRlTGVmdBAVEhAKDGV5ZVdpZGVSaWdodBAWEg4KCmphd0ZvcndhcmQQFxIL",
            "CgdqYXdMZWZ0EBgSCwoHamF3T3BlbhAZEgwKCGphd1JpZ2h0EBoSDgoKbW91",
            "dGhDbG9zZRAbEhMKD21vdXRoRGltcGxlTGVmdBAcEhQKEG1vdXRoRGltcGxl",
            "UmlnaHQQHRISCg5tb3V0aEZyb3duTGVmdBAeEhMKD21vdXRoRnJvd25SaWdo",
            "dBAfEg8KC21vdXRoRnVubmVsECASDQoJbW91dGhMZWZ0ECESFgoSbW91dGhM",
            "b3dlckRvd25MZWZ0ECISFwoTbW91dGhMb3dlckRvd25SaWdodBAjEhIKDm1v",
            "dXRoUHJlc3NMZWZ0ECQSEwoPbW91dGhQcmVzc1JpZ2h0ECUSDwoLbW91dGhQ",
            "dWNrZXIQJhIOCgptb3V0aFJpZ2h0ECcSEgoObW91dGhSb2xsTG93ZXIQKBIS",
            "Cg5tb3V0aFJvbGxVcHBlchApEhMKD21vdXRoU2hydWdMb3dlchAqEhMKD21v",
            "dXRoU2hydWdVcHBlchArEhIKDm1vdXRoU21pbGVMZWZ0ECwSEwoPbW91dGhT",
            "bWlsZVJpZ2h0EC0SFAoQbW91dGhTdHJldGNoTGVmdBAuEhUKEW1vdXRoU3Ry",
            "ZXRjaFJpZ2h0EC8SFAoQbW91dGhVcHBlclVwTGVmdBAwEhUKEW1vdXRoVXBw",
            "ZXJVcFJpZ2h0EDESEQoNbm9zZVNuZWVyTGVmdBAyEhIKDm5vc2VTbmVlclJp",
            "Z2h0EDMSDQoJdG9uZ3VlT3V0EDQSFAoQYmxlbmRzaGFwZUxlbmd0aBA1YgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HumanLandmarks.LandmarkReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HumanLandmarks.FaceResults), global::HumanLandmarks.FaceResults.Parser, new[]{ "Landmarks", "Blendshapes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HumanLandmarks.Blendshapes), global::HumanLandmarks.Blendshapes.Parser, new[]{ "Scores" }, null, new[]{ typeof(global::HumanLandmarks.Blendshapes.Types.BlendshapesIndex) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FaceResults : pb::IMessage<FaceResults>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FaceResults> _parser = new pb::MessageParser<FaceResults>(() => new FaceResults());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FaceResults> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HumanLandmarks.FaceResultsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults(FaceResults other) : this() {
      landmarks_ = other.landmarks_.Clone();
      blendshapes_ = other.blendshapes_ != null ? other.blendshapes_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults Clone() {
      return new FaceResults(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HumanLandmarks.Landmark> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HumanLandmarks.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HumanLandmarks.Landmark> landmarks_ = new pbc::RepeatedField<global::HumanLandmarks.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HumanLandmarks.Landmark> Landmarks {
      get { return landmarks_; }
    }

    /// <summary>Field number for the "blendshapes" field.</summary>
    public const int BlendshapesFieldNumber = 2;
    private global::HumanLandmarks.Blendshapes blendshapes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HumanLandmarks.Blendshapes Blendshapes {
      get { return blendshapes_; }
      set {
        blendshapes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FaceResults);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FaceResults other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      if (!object.Equals(Blendshapes, other.Blendshapes)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (blendshapes_ != null) hash ^= Blendshapes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (blendshapes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Blendshapes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (blendshapes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Blendshapes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (blendshapes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Blendshapes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FaceResults other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      if (other.blendshapes_ != null) {
        if (blendshapes_ == null) {
          Blendshapes = new global::HumanLandmarks.Blendshapes();
        }
        Blendshapes.MergeFrom(other.Blendshapes);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
          case 18: {
            if (blendshapes_ == null) {
              Blendshapes = new global::HumanLandmarks.Blendshapes();
            }
            input.ReadMessage(Blendshapes);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
          case 18: {
            if (blendshapes_ == null) {
              Blendshapes = new global::HumanLandmarks.Blendshapes();
            }
            input.ReadMessage(Blendshapes);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Blendshapes : pb::IMessage<Blendshapes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Blendshapes> _parser = new pb::MessageParser<Blendshapes>(() => new Blendshapes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Blendshapes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HumanLandmarks.FaceResultsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes(Blendshapes other) : this() {
      scores_ = other.scores_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes Clone() {
      return new Blendshapes(this);
    }

    /// <summary>Field number for the "scores" field.</summary>
    public const int ScoresFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_scores_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> scores_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Scores {
      get { return scores_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Blendshapes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Blendshapes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!scores_.Equals(other.scores_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= scores_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      scores_.WriteTo(output, _repeated_scores_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      scores_.WriteTo(ref output, _repeated_scores_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += scores_.CalculateSize(_repeated_scores_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Blendshapes other) {
      if (other == null) {
        return;
      }
      scores_.Add(other.scores_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            scores_.AddEntriesFrom(input, _repeated_scores_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            scores_.AddEntriesFrom(ref input, _repeated_scores_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Blendshapes message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum BlendshapesIndex {
        [pbr::OriginalName("_neutral")] Neutral = 0,
        [pbr::OriginalName("browDownLeft")] BrowDownLeft = 1,
        [pbr::OriginalName("browDownRight")] BrowDownRight = 2,
        [pbr::OriginalName("browInnerUp")] BrowInnerUp = 3,
        [pbr::OriginalName("browOuterUpLeft")] BrowOuterUpLeft = 4,
        [pbr::OriginalName("browOuterUpRight")] BrowOuterUpRight = 5,
        [pbr::OriginalName("cheekPuff")] CheekPuff = 6,
        [pbr::OriginalName("cheekSquintLeft")] CheekSquintLeft = 7,
        [pbr::OriginalName("cheekSquintRight")] CheekSquintRight = 8,
        [pbr::OriginalName("eyeBlinkLeft")] EyeBlinkLeft = 9,
        [pbr::OriginalName("eyeBlinkRight")] EyeBlinkRight = 10,
        [pbr::OriginalName("eyeLookDownLeft")] EyeLookDownLeft = 11,
        [pbr::OriginalName("eyeLookDownRight")] EyeLookDownRight = 12,
        [pbr::OriginalName("eyeLookInLeft")] EyeLookInLeft = 13,
        [pbr::OriginalName("eyeLookInRight")] EyeLookInRight = 14,
        [pbr::OriginalName("eyeLookOutLeft")] EyeLookOutLeft = 15,
        [pbr::OriginalName("eyeLookOutRight")] EyeLookOutRight = 16,
        [pbr::OriginalName("eyeLookUpLeft")] EyeLookUpLeft = 17,
        [pbr::OriginalName("eyeLookUpRight")] EyeLookUpRight = 18,
        [pbr::OriginalName("eyeSquintLeft")] EyeSquintLeft = 19,
        [pbr::OriginalName("eyeSquintRight")] EyeSquintRight = 20,
        [pbr::OriginalName("eyeWideLeft")] EyeWideLeft = 21,
        [pbr::OriginalName("eyeWideRight")] EyeWideRight = 22,
        [pbr::OriginalName("jawForward")] JawForward = 23,
        [pbr::OriginalName("jawLeft")] JawLeft = 24,
        [pbr::OriginalName("jawOpen")] JawOpen = 25,
        [pbr::OriginalName("jawRight")] JawRight = 26,
        [pbr::OriginalName("mouthClose")] MouthClose = 27,
        [pbr::OriginalName("mouthDimpleLeft")] MouthDimpleLeft = 28,
        [pbr::OriginalName("mouthDimpleRight")] MouthDimpleRight = 29,
        [pbr::OriginalName("mouthFrownLeft")] MouthFrownLeft = 30,
        [pbr::OriginalName("mouthFrownRight")] MouthFrownRight = 31,
        [pbr::OriginalName("mouthFunnel")] MouthFunnel = 32,
        [pbr::OriginalName("mouthLeft")] MouthLeft = 33,
        [pbr::OriginalName("mouthLowerDownLeft")] MouthLowerDownLeft = 34,
        [pbr::OriginalName("mouthLowerDownRight")] MouthLowerDownRight = 35,
        [pbr::OriginalName("mouthPressLeft")] MouthPressLeft = 36,
        [pbr::OriginalName("mouthPressRight")] MouthPressRight = 37,
        [pbr::OriginalName("mouthPucker")] MouthPucker = 38,
        [pbr::OriginalName("mouthRight")] MouthRight = 39,
        [pbr::OriginalName("mouthRollLower")] MouthRollLower = 40,
        [pbr::OriginalName("mouthRollUpper")] MouthRollUpper = 41,
        [pbr::OriginalName("mouthShrugLower")] MouthShrugLower = 42,
        [pbr::OriginalName("mouthShrugUpper")] MouthShrugUpper = 43,
        [pbr::OriginalName("mouthSmileLeft")] MouthSmileLeft = 44,
        [pbr::OriginalName("mouthSmileRight")] MouthSmileRight = 45,
        [pbr::OriginalName("mouthStretchLeft")] MouthStretchLeft = 46,
        [pbr::OriginalName("mouthStretchRight")] MouthStretchRight = 47,
        [pbr::OriginalName("mouthUpperUpLeft")] MouthUpperUpLeft = 48,
        [pbr::OriginalName("mouthUpperUpRight")] MouthUpperUpRight = 49,
        [pbr::OriginalName("noseSneerLeft")] NoseSneerLeft = 50,
        [pbr::OriginalName("noseSneerRight")] NoseSneerRight = 51,
        [pbr::OriginalName("tongueOut")] TongueOut = 52,
        [pbr::OriginalName("blendshapeLength")] BlendshapeLength = 53,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
