// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: kinect_pose_landmarks.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HumanLandmarks {

  /// <summary>Holder for reflection information generated from kinect_pose_landmarks.proto</summary>
  public static partial class KinectPoseLandmarksReflection {

    #region Descriptor
    /// <summary>File descriptor for kinect_pose_landmarks.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KinectPoseLandmarksReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtraW5lY3RfcG9zZV9sYW5kbWFya3MucHJvdG8SDmh1bWFuTGFuZG1hcmtz",
            "Gg5sYW5kbWFyay5wcm90byLLBAoTS2luZWN0UG9zZUxhbmRtYXJrcxIrCgls",
            "YW5kbWFya3MYASADKAsyGC5odW1hbkxhbmRtYXJrcy5MYW5kbWFyayKGBAoN",
            "TGFuZG1hcmtJbmRleBIKCgZQRUxWSVMQABIPCgtTUElORV9OQVZBTBABEg8K",
            "C1NQSU5FX0NIRVNUEAISCAoETkVDSxADEhEKDUNMQVZJQ0xFX0xFRlQQBBIR",
            "Cg1TSE9VTERFUl9MRUZUEAUSDgoKRUxCT1dfTEVGVBAGEg4KCldSSVNUX0xF",
            "RlQQBxINCglIQU5EX0xFRlQQCBIQCgxIQU5EVElQX0xFRlQQCRIOCgpUSFVN",
            "Ql9MRUZUEAoSEgoOQ0xBVklDTEVfUklHSFQQCxISCg5TSE9VTERFUl9SSUdI",
            "VBAMEg8KC0VMQk9XX1JJR0hUEA0SDwoLV1JJU1RfUklHSFQQDhIOCgpIQU5E",
            "X1JJR0hUEA8SEQoNSEFORFRJUF9SSUdIVBAQEg8KC1RIVU1CX1JJR0hUEBES",
            "DAoISElQX0xFRlQQEhINCglLTkVFX0xFRlQQExIOCgpBTktMRV9MRUZUEBQS",
            "DQoJRk9PVF9MRUZUEBUSDQoJSElQX1JJR0hUEBYSDgoKS05FRV9SSUdIVBAX",
            "Eg8KC0FOS0xFX1JJR0hUEBgSDgoKRk9PVF9SSUdIVBAZEggKBEhFQUQQGhII",
            "CgROT1NFEBsSDAoIRVlFX0xFRlQQHBIMCghFQVJfTEVGVBAdEg0KCUVZRV9S",
            "SUdIVBAeEg0KCUVBUl9SSUdIVBAfYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HumanLandmarks.LandmarkReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HumanLandmarks.KinectPoseLandmarks), global::HumanLandmarks.KinectPoseLandmarks.Parser, new[]{ "Landmarks" }, null, new[]{ typeof(global::HumanLandmarks.KinectPoseLandmarks.Types.LandmarkIndex) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class KinectPoseLandmarks : pb::IMessage<KinectPoseLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KinectPoseLandmarks> _parser = new pb::MessageParser<KinectPoseLandmarks>(() => new KinectPoseLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KinectPoseLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HumanLandmarks.KinectPoseLandmarksReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KinectPoseLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KinectPoseLandmarks(KinectPoseLandmarks other) : this() {
      landmarks_ = other.landmarks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KinectPoseLandmarks Clone() {
      return new KinectPoseLandmarks(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HumanLandmarks.Landmark> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HumanLandmarks.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HumanLandmarks.Landmark> landmarks_ = new pbc::RepeatedField<global::HumanLandmarks.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HumanLandmarks.Landmark> Landmarks {
      get { return landmarks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KinectPoseLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KinectPoseLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KinectPoseLandmarks other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the KinectPoseLandmarks message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum LandmarkIndex {
        [pbr::OriginalName("PELVIS")] Pelvis = 0,
        [pbr::OriginalName("SPINE_NAVAL")] SpineNaval = 1,
        [pbr::OriginalName("SPINE_CHEST")] SpineChest = 2,
        [pbr::OriginalName("NECK")] Neck = 3,
        [pbr::OriginalName("CLAVICLE_LEFT")] ClavicleLeft = 4,
        [pbr::OriginalName("SHOULDER_LEFT")] ShoulderLeft = 5,
        [pbr::OriginalName("ELBOW_LEFT")] ElbowLeft = 6,
        [pbr::OriginalName("WRIST_LEFT")] WristLeft = 7,
        [pbr::OriginalName("HAND_LEFT")] HandLeft = 8,
        [pbr::OriginalName("HANDTIP_LEFT")] HandtipLeft = 9,
        [pbr::OriginalName("THUMB_LEFT")] ThumbLeft = 10,
        [pbr::OriginalName("CLAVICLE_RIGHT")] ClavicleRight = 11,
        [pbr::OriginalName("SHOULDER_RIGHT")] ShoulderRight = 12,
        [pbr::OriginalName("ELBOW_RIGHT")] ElbowRight = 13,
        [pbr::OriginalName("WRIST_RIGHT")] WristRight = 14,
        [pbr::OriginalName("HAND_RIGHT")] HandRight = 15,
        [pbr::OriginalName("HANDTIP_RIGHT")] HandtipRight = 16,
        [pbr::OriginalName("THUMB_RIGHT")] ThumbRight = 17,
        [pbr::OriginalName("HIP_LEFT")] HipLeft = 18,
        [pbr::OriginalName("KNEE_LEFT")] KneeLeft = 19,
        [pbr::OriginalName("ANKLE_LEFT")] AnkleLeft = 20,
        [pbr::OriginalName("FOOT_LEFT")] FootLeft = 21,
        [pbr::OriginalName("HIP_RIGHT")] HipRight = 22,
        [pbr::OriginalName("KNEE_RIGHT")] KneeRight = 23,
        [pbr::OriginalName("ANKLE_RIGHT")] AnkleRight = 24,
        [pbr::OriginalName("FOOT_RIGHT")] FootRight = 25,
        [pbr::OriginalName("HEAD")] Head = 26,
        [pbr::OriginalName("NOSE")] Nose = 27,
        [pbr::OriginalName("EYE_LEFT")] EyeLeft = 28,
        [pbr::OriginalName("EAR_LEFT")] EarLeft = 29,
        [pbr::OriginalName("EYE_RIGHT")] EyeRight = 30,
        [pbr::OriginalName("EAR_RIGHT")] EarRight = 31,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
